**Transformation de la DB des urls en dataframe pandas**

In [48]:
import sqlite3
import pandas as pd
import os

db_path = "..\\data\\speeches.db"
conn=sqlite3.connect(db_path)
df1=pd.read_sql_query("Select * from Speeches",conn)
conn.close()

In [49]:
df1.head(3)

,id,url,title,date,nbr_sentences,nbr_words,nbr_seconds,categories
0,1,https://rollcall.com/factbase/trump/transcript...,Speech: Donald Trump Addresses Service Members...,"October 5, 2025",693,6902,2636,"[""Armed Forces"", ""Waterway and Maritime Transp..."
1,2,https://rollcall.com/factbase/trump/transcript...,Speech: Donald Trump Addresses Military Leader...,"September 30, 2025",1031,12529,4261,"[""Politics"", ""Military Equipment"", ""Government..."
2,3,https://rollcall.com/factbase/trump/transcript...,Speech: JD Vance Discusses Tax Policy and Publ...,"September 24, 2025",,,,"[""Government"", ""Crime"", ""Police"", ""Law Enforce..."

In [50]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885 entries, 0 to 884
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             885 non-null    int64
 1   url            885 non-null    object
 2   title          885 non-null    object
 3   date           885 non-null    object
 4   nbr_sentences  885 non-null    object
 5   nbr_words      885 non-null    object
 6   nbr_seconds    885 non-null    object
 7   categories     885 non-null    object
dtypes: int64(1), object(7)
memory usage: 55.4+ KB

### Convertion of some variables into numeric/datetime

In [51]:
df1["nbr_words"]=pd.to_numeric(df1["nbr_words"], errors= "coerce",downcast="integer")
df1["nbr_sentences"]=pd.to_numeric(df1["nbr_sentences"], errors="coerce", downcast="integer")
df1["nbr_seconds"]=pd.to_numeric(df1["nbr_seconds"], errors="coerce", downcast="integer")

df1["date"]=pd.to_datetime(df1["date"], errors="coerce")

### Checking of the database and treatment of missing value

In [52]:
df1.isna().sum().sort_values(ascending=False)*100/df1.shape[0]

date             2.372881
nbr_seconds      2.372881
nbr_sentences    0.677966
nbr_words        0.677966
title            0.000000
url              0.000000
id               0.000000
categories       0.000000
dtype: float64

In [53]:
df1.fillna({"nbr_sentences" : df1["nbr_sentences"].mean(),
            "nbr_seconds": df1["nbr_seconds"].mean(),
            "nbr_words": df1["nbr_words"].mean()
}, inplace=True)

In [54]:
df1.head(2)

,id,url,title,date,nbr_sentences,nbr_words,nbr_seconds,categories
0,1,https://rollcall.com/factbase/trump/transcript...,Speech: Donald Trump Addresses Service Members...,2025-10-05,693.0,6902.0,2636.0,"[""Armed Forces"", ""Waterway and Maritime Transp..."
1,2,https://rollcall.com/factbase/trump/transcript...,Speech: Donald Trump Addresses Military Leader...,2025-09-30,1031.0,12529.0,4261.0,"[""Politics"", ""Military Equipment"", ""Government..."

### Some basis statistics

In [55]:
df1.columns

Index(['id', 'url', 'title', 'date', 'nbr_sentences', 'nbr_words',
       'nbr_seconds', 'categories'],
      dtype='object')

In [60]:
df1[["nbr_sentences","nbr_words","nbr_seconds" ]].describe().round(2)

       nbr_sentences  nbr_words  nbr_seconds
count         885.00     885.00       885.00
mean          769.85    7915.07      3241.95
std           438.84    4273.45      1500.80
min             1.00       3.00         1.00
25%           422.00    4721.00      2192.00
50%           765.00    7761.00      3190.00
75%          1092.00   10832.00      4310.00
max          2285.00   28090.00      7295.00

In [68]:
df1["categories"].head(5)

0    ["Armed Forces", "Waterway and Maritime Transp...
1    ["Politics", "Military Equipment", "Government...
2    ["Government", "Crime", "Police", "Law Enforce...
3    ["Economy, Business and Finance", "Crime", "In...
4    ["Crime", "Religion", "Crime, Law and Justice"...
Name: categories, dtype: object

In [67]:
df1["categories"].value_counts()

categories
["Human Rights", "Politics"]                                                                                                                                                                                                                                                       146
["Defense", "Human Rights", "Politics"]                                                                                                                                                                                                                                             61
["Election", "Human Rights", "Politics"]                                                                                                                                                                                                                                            27
["Election", "Defense", "Human Rights", "Politics"]                                                                                                                                                                                                                                 20
["Politics", "Defense"]                                                                                                                                                                                                                                                             13
                                                                                                                                                                                                                                                                                  ...
["Economy, Business and Finance", "Government Policy", "Politics", "Energy and Resource", "Nuclear Policy", "Products and Services", "Coal"]                                                                                                                                         1
["Religion", "Belief Systems", "Politics", "Christianity", "Crime, Law and Justice", "Judiciary", "Court"]                                                                                                                                                                           1
["Politics", "Military Equipment", "Government", "Armed Conflict", "Conflict, War and Peace", "Military Weaponry", "Defence"]                                                                                                                                                        1
["Armed Forces", "Waterway and Maritime Transport", "Politics", "Military Equipment", "Economy, Business and Finance", "Government", "Military Service", "Armed Conflict", "Conflict, War and Peace", "Transport", "Military Weaponry", "Products and Services", "Defence"]          1
["Company Information", "Market and Exchange", "Unrest, Conflicts and War", "Macro Economics", "Economy, Business and Finance", "Economy (General)", "Securities", "Merger, Acquisition and Takeover", "Politics", "Election", "Human Rights", "International (Foreign) Trade"]      1
Name: count, Length: 459, dtype: int64